---
root: true
extends:
  - airbnb-base
  - plugin:import/errors
  - prettier
plugins:
  - no-not-accumulator-reassign
  - prettier
env:
    node: true

globals:
  NSImage: false
  NSPasteboard: false
  NSPasteboardTypePNG: false
  NSPasteboardTypeTIFF: false
  MSImageData: false
rules:
  no-not-accumulator-reassign/no-not-accumulator-reassign: [2, ['reduce'], {props: true}]
  import/no-unresolved:
      - error
      - commonjs: true
        caseSensitive: true
        ignore:
          - '^sketch(\/|$)'